/**
 * Inventory items with name, volume (cubic feet), and category for room filtering.
 * Categories: Bedroom, Living Room, Dining Room, Kitchen, Appliances, Office, Garage, Patio Furniture, Boxes, Miscellaneous, Nursery, Attic, Basement, Play Room, Military
 */
function getCategory(name) {
  const n = (name || '').toUpperCase();
  if (/BED|MATTRESS|DRESSER|NIGHT STAND|ARMOIRE|HEADBOARD|BOX SPRING|CANOPY|TRUNDLE|VANITY, DRESSER|CHEST OF DRAWERS/i.test(n)) return 'Bedroom';
  if (/SOFA|LOVESEAT|SECTIONAL|CHAIR.*ARM|CHAIR.*CLUB|CHAIR.*LOUNGE|RECLINER|ROCKER|OVERSTUFFED|COFFEE TABLE|END TABLE|SIDE TABLE|ENTERTAINMENT CENTER|OTTOMAN|PAPIZON|CHAISE/i.test(n)) return 'Living Room';
  if (/DINING TABLE|DINING CHAIR|DINING BENCH|BUFFET|CHINA CAB|BREAKFRONT|HUTCH|SIDEBOARD|PEDESTAL/i.test(n)) return 'Dining Room';
  if (/DISHWASHER|MICROWAVE|REFRIGERATOR|STOVE|KITCHEN|CABINET.*MEDIUM|CABINET.*SMALL|WINE RACK/i.test(n)) return 'Kitchen';
  if (/WASHING MACHINE|DRYER|FREEZER|AIR CONDITION|WASHER\/DRYER/i.test(n)) return 'Appliances';
  if (/DESK|FILE CABINET|COPIER|COMPUTER|PRINTER|CREDENZA|FILE BOX|SERVER|FAX MACHINE/i.test(n)) return 'Office';
  if (/LAWNMOWER|TOOL BOX|MOTORCYCLE|BIKE|GARBAGE CAN|WHEELBARROW|EDGER|SHOP-VAC|TIRE|TOOLS GARDEN|WORK BENCH/i.test(n)) return 'Garage';
  if (/PATIO|BARBECUE|UMBRELLA|GRILL/i.test(n)) return 'Patio Furniture';
  if (/^BOX\s|BOX,|BOX LAMP|BOX BOOK/i.test(n)) return 'Boxes';
  if (/CRIB|CRADLE|CHANGING TABLE|GLIDER CHAIR|STROLLER|PLAYPEN|TODDLER BED|NURSERY/i.test(n)) return 'Nursery';
  if (/TOY|TRAMPOLINE|PLAY HOUSE|CAR TOY|TOY CHEST|TOY CAR/i.test(n)) return 'Play Room';
  if (/ATTIC/i.test(n)) return 'Attic';
  if (/BASEMENT/i.test(n)) return 'Basement';
  if (/MILITARY|KIT BAG/i.test(n)) return 'Military';
  return 'Miscellaneous';
}

const INVENTORY_ITEMS = [
  { name: '12 CUBE ORGANIZER', volume: 15 },
  { name: '16 CUBE ORGANIZER', volume: 30 },
  { name: '4 CUBE ORGANIZER', volume: 6 },
  { name: '6 CUBE ORGANIZER', volume: 8 },
  { name: '8 CUBE ORGANIZER', volume: 10 },
  { name: 'A HOUSEHOLD GOODS - 1000 LBS', volume: 200 },
  { name: 'A HOUSEHOLD GOODS - 1500 LBS', volume: 250 },
  { name: 'A HOUSEHOLD GOODS - 2600 LBS', volume: 400 },
  { name: 'A HOUSEHOLD GOODS - 3900 LBS', volume: 600 },
  { name: 'A HOUSEHOLD GOODS - 5800 LBS', volume: 892 },
  { name: 'A HOUSEHOLD GOODS - 8500 LBS', volume: 1308 },
  { name: 'A STORAGE UNIT - 5X10 - 1750', volume: 400 },
  { name: 'A-STORAGE UNIT - 10X10 - 3500', volume: 800 },
  { name: 'A-STORAGE UNIT - 10X15 - 5000', volume: 1200 },
  { name: 'A-STORAGE UNIT - 10X20 - 7000', volume: 1600 },
  { name: 'A-STORAGE UNIT - 10X25 - 8500', volume: 2000 },
  { name: 'A-STORAGE UNIT - 10X30 - 10000', volume: 2400 },
  { name: 'AIR CONDITION, LG', volume: 14 },
  { name: 'AIR CONDITION, SM.', volume: 8 },
  { name: 'AQUARIUM STAND, LG.', volume: 50 },
  { name: 'AQUARIUM STAND, SM.', volume: 16 },
  { name: 'AQUARIUM, 10 GAL', volume: 5 },
  { name: 'AQUARIUM, 20 GAL', volume: 10 },
  { name: 'AQUARIUM, 55 GAL', volume: 25 },
  { name: 'ARMOIRE, LARGE', volume: 65 },
  { name: 'ARMOIRE, REGULAR', volume: 55 },
  { name: 'ARMOIRE, SMALL', volume: 35 },
  { name: 'BAKERS RACK', volume: 27 },
  { name: 'BAR, 3X4X2', volume: 24 },
  { name: 'BAR, STOOL', volume: 5 },
  { name: 'BARBECUE GRILL', volume: 20 },
  { name: 'BARBECUE GRILL, SMALL', volume: 8 },
  { name: 'BED - BOX SPRING', volume: 20 },
  { name: 'BED CANOPY', volume: 21 },
  { name: 'BED FRAME', volume: 10 },
  { name: 'BED, BRIDGE HEADBOARD', volume: 45 },
  { name: 'BED, BRIDGELIGHT', volume: 95 },
  { name: 'BED, BUNK (WITH MATTRESS)', volume: 70 },
  { name: 'BED, CAPTAIN (WITH MATTRESS)', volume: 50 },
  { name: 'BED, DAY', volume: 40 },
  { name: 'BED, DOUBLE (WITH MATTRESS/BOX SPRING)', volume: 55 },
  { name: 'BED, DOUBLE (WITH MATTRESSES)', volume: 55 },
  { name: 'BED, FOOTBOARD', volume: 10 },
  { name: 'BED, FULL (WITH MATTRESS)', volume: 50 },
  { name: 'BED, FULL (WITH MATTRESS/BOX SPRING)', volume: 50 },
  { name: 'BED, HEADBOARD', volume: 10 },
  { name: 'BED, KING (WITH MATTRESS)', volume: 70 },
  { name: 'BED, KING (WITH MATTRESS/BOX SPRING)', volume: 70 },
  { name: 'BED, LARGE HEADBOARD', volume: 25 },
  { name: 'BED, PLATFORM', volume: 45 },
  { name: 'BED, POST', volume: 5 },
  { name: 'BED, QUEEN (WITH MATTRESS)', volume: 65 },
  { name: 'BED, QUEEN (WITH MATTRESS/BOX SPRING)', volume: 65 },
  { name: 'BED, SINGLE (WITH MATTRESS)', volume: 45 },
  { name: 'BED, SINGLE (WITH MATTRESS/BOX SPRING)', volume: 45 },
  { name: 'BED, TRUNDLE', volume: 20 },
  { name: 'BED, TWIN (WITH MATTRESS)', volume: 40 },
  { name: 'BED, TWIN (WITH MATTRESS/BOX SPRING)', volume: 40 },
  { name: 'BED, WATER Q/K', volume: 75 },
  { name: 'BEEN BAG, SMALL', volume: 16 },
  { name: 'BENCH, LARGE', volume: 15 },
  { name: 'BENCH, SMALL', volume: 8 },
  { name: 'BIKE, ADULT', volume: 12 },
  { name: 'BIKE, CHILD', volume: 7 },
  { name: 'BOOK SHELF', volume: 25 },
  { name: 'BOOK SHELF, MED.', volume: 10 },
  { name: 'BOOK SHELF, SMALL', volume: 8 },
  { name: 'BOOKCASE 6X3', volume: 25 },
  { name: 'BOOKCASE, SM.', volume: 10 },
  { name: 'BOX LAMP', volume: 13 },
  { name: 'BOX, BOOK/SMALL', volume: 4 },
  { name: 'BOX, CHINA/DISH', volume: 6 },
  { name: 'BOX, LARGE. PBO', volume: 5 },
  { name: 'BOX, LINEN/MEDIUM', volume: 3 },
  { name: 'BOX, MED/LG PBO', volume: 4 },
  { name: 'BOX, SMALL PBO', volume: 2 },
  { name: 'BOX, WARDROBE - (15 CU. FT.)', volume: 16 },
  { name: 'BREAKFRONT 1 PIECE', volume: 40 },
  { name: 'BUFFET, BASE', volume: 35 },
  { name: 'BUFFET, TOP', volume: 30 },
  { name: 'CABINET, CORNER', volume: 40 },
  { name: 'CABINET, MEDIUM', volume: 15 },
  { name: 'CABINET, SMALL', volume: 10 },
  { name: 'CAR TOY (FOR CHILD)', volume: 30 },
  { name: 'CARPET 8X10', volume: 10 },
  { name: 'CARPET, AREA (SM.)', volume: 5 },
  { name: 'CD HOLDER', volume: 2 },
  { name: 'CD PLAYER (PBO)', volume: 1 },
  { name: 'CHAIR, ARM', volume: 17 },
  { name: 'CHAIR, CLUB', volume: 20 },
  { name: 'CHAIR, DINING', volume: 7 },
  { name: 'CHAIR, FOLDING', volume: 3 },
  { name: 'CHAIR, HIGH', volume: 6 },
  { name: 'CHAIR, HIGH BACK', volume: 12 },
  { name: 'CHAIR, KITCHEN', volume: 7 },
  { name: 'CHAIR, LOUNGE', volume: 23 },
  { name: 'CHAIR, OFFICE (SM.)', volume: 6 },
  { name: 'CHAIR, OFFICE,(LG.)', volume: 13 },
  { name: 'CHAIR, OVERSTUFFED', volume: 28 },
  { name: 'CHAIR, PAPIZON', volume: 20 },
  { name: 'CHAIR, RECLINER', volume: 21 },
  { name: 'CHAIR, ROCKER', volume: 16 },
  { name: 'CHAIR, SINGLE', volume: 7 },
  { name: 'CHAIR, STACKABLE', volume: 5 },
  { name: 'CHAIR, WICKER', volume: 18 },
  { name: 'CHAISE LOUNGE', volume: 16 },
  { name: 'CHANDELIER, LG.', volume: 20 },
  { name: 'CHANDELIER, SM.', volume: 10 },
  { name: 'CHANGING TABLE', volume: 12 },
  { name: 'CHEST OF DRAWERS', volume: 30 },
  { name: 'CHEST, CEDAR', volume: 20 },
  { name: 'CHEST, MEDIUM', volume: 28 },
  { name: 'CHEST, SMALL', volume: 19 },
  { name: 'CHEST, TOY', volume: 20 },
  { name: 'CHILD, CHAIRS', volume: 10 },
  { name: 'CHILD, TABLE', volume: 8 },
  { name: 'CHILD, TOY', volume: 5 },
  { name: 'CHINA CAB, 1 PIECE', volume: 50 },
  { name: 'CHINA CAB, 2 PIECE', volume: 65 },
  { name: 'CLOCK, GRANGFATHER', volume: 35 },
  { name: 'CLOCK, WALL', volume: 3 },
  { name: 'COAT RACK', volume: 10 },
  { name: 'COMPUTER CHAIR', volume: 9 },
  { name: 'COMPUTER DESK', volume: 18 },
  { name: 'COMPUTER SCREEN (PBO)', volume: 5 },
  { name: 'COMPUTER SYSTEM (PBO)', volume: 10 },
  { name: 'COPIER, REG. OFFICE', volume: 30 },
  { name: 'COPIER, TABLE TOP', volume: 16 },
  { name: 'CORNER CABINET', volume: 35 },
  { name: 'CRADLE', volume: 20 },
  { name: 'CREDENZA', volume: 30 },
  { name: 'CRIB', volume: 25 },
  { name: 'CRIB MINI', volume: 25 },
  { name: 'CURIO CABINET', volume: 22 },
  { name: 'DESK CHAIR, LARGE', volume: 12 },
  { name: 'DESK CHAIR, SMALL', volume: 8 },
  { name: 'DESK, DOUBLE', volume: 35 },
  { name: 'DESK, EXECUTIVE', volume: 65 },
  { name: 'DESK, HUTCH', volume: 13 },
  { name: 'DESK, REGULAR', volume: 30 },
  { name: 'DESK, RETURN (L-SHAPE)', volume: 40 },
  { name: 'DESK, SMALL', volume: 16 },
  { name: 'DINING BENCH', volume: 7 },
  { name: 'DINING CHAIR', volume: 6 },
  { name: 'DINING CHAIR + ARM', volume: 9 },
  { name: 'DINING TABLE', volume: 35 },
  { name: 'DISHWASHER', volume: 25 },
  { name: 'DRESSER, CHILD', volume: 16 },
  { name: 'DRESSER, DOUBLE', volume: 40 },
  { name: 'DRESSER, MIRROR', volume: 5 },
  { name: 'DRESSER, SINGLE', volume: 30 },
  { name: 'DRESSER, TRIPLE', volume: 55 },
  { name: 'DRYER', volume: 35 },
  { name: 'DVD/VCR (PBO)', volume: 1 },
  { name: 'EDGER', volume: 7 },
  { name: 'ELECTRIC FIREPLACE', volume: 10 },
  { name: 'ELLIPTICAL', volume: 50 },
  { name: 'ENTERTAINMENT CENTER, LG', volume: 45 },
  { name: 'ENTERTAINMENT CENTER, REG', volume: 25 },
  { name: 'ENTERTAINMENT CENTER, SM', volume: 18 },
  { name: 'EXCERCISE BIKE', volume: 22 },
  { name: 'EXCERCISE EQUIP LARGE', volume: 45 },
  { name: 'EXCERCISE EQUIP SMALL', volume: 22 },
  { name: 'FAN, FLOOR', volume: 5 },
  { name: 'FAX MACHINE (PBO)', volume: 1 },
  { name: 'FILE BOX- LEGAL', volume: 6 },
  { name: 'FILE BOX- LETTER', volume: 3 },
  { name: 'FILE CABINET, 2 DRAWER', volume: 8 },
  { name: 'FILE CABINET, 4 DRAWER', volume: 16 },
  { name: 'FILE CABINET, 5 DRAWER', volume: 32 },
  { name: 'FILE CABINET, LG.', volume: 45 },
  { name: 'FILE CABINET, SM.', volume: 20 },
  { name: 'FOOT STOOL', volume: 2 },
  { name: 'FREEZER, LARGE', volume: 65 },
  { name: 'FREEZER, MEDIUM', volume: 40 },
  { name: 'FREEZER, SMALL', volume: 20 },
  { name: 'FREEZER, XLG.', volume: 80 },
  { name: 'FULL MATTRESS ONLY', volume: 30 },
  { name: 'FUTON', volume: 50 },
  { name: 'GAME TABLE', volume: 12 },
  { name: 'GAMING CHAIR', volume: 10 },
  { name: 'GARBAGE CAN', volume: 3 },
  { name: 'GLIDER CHAIR', volume: 35 },
  { name: 'GOLF BAG', volume: 4 },
  { name: 'GUITAR (IN CASE)', volume: 5 },
  { name: 'HAMPER', volume: 5 },
  { name: 'HUTCH', volume: 23 },
  { name: 'INSTEP STROLLER', volume: 16 },
  { name: 'IRONING BOARD', volume: 2 },
  { name: 'JEWELRY CABINET', volume: 15 },
  { name: 'KAYAK (UP TO 8 FOOT)', volume: 53 },
  { name: 'KEYBOARD (ORGAN)', volume: 13 },
  { name: 'KING MATTRESS ONLY', volume: 45 },
  { name: 'KIT BAG', volume: 10 },
  { name: 'KITCHEN BENCH', volume: 7 },
  { name: 'LADDER TO 10', volume: 9 },
  { name: 'LADDER TO 7', volume: 7 },
  { name: 'LADDER, EXTENSION', volume: 18 },
  { name: 'LAMP, FLOOR (PBO)', volume: 7 },
  { name: 'LAMP, TABLE (PBO)', volume: 3 },
  { name: 'LAWNMOWER, PUSH', volume: 23 },
  { name: 'LAWNMOWER, RIDE', volume: 56 },
  { name: 'LOUNGE CHAIR', volume: 13 },
  { name: 'MAGAZINE RACK', volume: 2 },
  { name: 'MATTRESS CAL KING', volume: 50 },
  { name: 'MATTRESS DBL/QN', volume: 35 },
  { name: 'MATTRESS KING', volume: 45 },
  { name: 'MATTRESS TWIN', volume: 25 },
  { name: 'MATTRESS TWIN XL', volume: 28 },
  { name: 'MICROWAVE CART', volume: 5 },
  { name: 'MICROWAVE, STANDARD', volume: 5 },
  { name: 'MIRROR, LG.', volume: 16 },
  { name: 'MIRROR, REGULAR', volume: 2 },
  { name: 'MOTORCYCLE (NOT INCLUD CRATE)', volume: 150 },
  { name: 'MUSICAL INSTRUMENT', volume: 16 },
  { name: 'NIGHT STAND', volume: 5 },
  { name: 'ORIENTAL SCREEN', volume: 10 },
  { name: 'OTTOMAN, LG.', volume: 11 },
  { name: 'OTTOMAN, SM.', volume: 6 },
  { name: 'PATIO CHAIR', volume: 12 },
  { name: 'PATIO COFFEE TABLE', volume: 5 },
  { name: 'PATIO END TABLE', volume: 3 },
  { name: 'PATIO SET, 5 PIECES', volume: 76 },
  { name: 'PATIO SOFA', volume: 16 },
  { name: 'PATIO SOFA', volume: 50 },
  { name: 'PATIO TABLE', volume: 31 },
  { name: 'PATIO UMBRELLA', volume: 7 },
  { name: 'PEDESTAL', volume: 7 },
  { name: 'PIANO BENCH', volume: 5 },
  { name: 'PIANO, BABYGRAND', volume: 75 },
  { name: 'PIANO, GRAND', volume: 85 },
  { name: 'PIANO, SPINET', volume: 55 },
  { name: 'PIANO, UPRIGHT', volume: 65 },
  { name: 'PICTURES, LARGE', volume: 5 },
  { name: 'PICTURES, MEDIUM', volume: 4 },
  { name: 'PICTURES, SMALL', volume: 3 },
  { name: 'PLANT ARTIFICIAL, LG.', volume: 22 },
  { name: 'PLANT ARTIFICIAL, SM.', volume: 16 },
  { name: 'PLANT STAND', volume: 5 },
  { name: 'PLASTIC BIN, LG.', volume: 8 },
  { name: 'PLASTIC BIN, MED.', volume: 6 },
  { name: 'PLASTIC BIN, SM.', volume: 5 },
  { name: 'PLASTIC DRAWERS', volume: 10 },
  { name: 'PLAY HOUSE (FOR KIDS)', volume: 12 },
  { name: 'PLAYPEN, FOLDING', volume: 7 },
  { name: 'POTTERY', volume: 6 },
  { name: 'PRINTER, SMALL', volume: 3 },
  { name: 'QUEEN MATTRESS ONLY', volume: 35 },
  { name: 'RECLINER', volume: 20 },
  { name: 'REFRIGERATOR DORMITY', volume: 13 },
  { name: 'REFRIGERATOR, SIDE/SIDE', volume: 70 },
  { name: 'REFRIGERATOR, UPRIGHT', volume: 55 },
  { name: 'RUG, AREA (SM.)', volume: 3 },
  { name: 'RUG, LARGE 8X10', volume: 10 },
  { name: 'SADDLE', volume: 5 },
  { name: 'SADDLE, LARGE', volume: 10 },
  { name: 'SAFE, SMALL', volume: 13 },
  { name: 'SCOOTER (NOT INCLUD CRATE)', volume: 100 },
  { name: 'SCREEN, FOLDING', volume: 10 },
  { name: 'SERVER', volume: 16 },
  { name: 'SEWING MACHINE, CONSOLE', volume: 12 },
  { name: 'SEWING MACHINE, PORTABLE', volume: 8 },
  { name: 'SHOE RACK', volume: 5 },
  { name: 'SHOP-VAC', volume: 5 },
  { name: 'SIDE TABLE', volume: 18 },
  { name: 'SIDEBOARD', volume: 10 },
  { name: 'SOFA TABLE', volume: 15 },
  { name: 'SOFA, 1 CHAIR', volume: 25 },
  { name: 'SOFA, 2 LOVESEAT', volume: 40 },
  { name: 'SOFA, 3 SEAT', volume: 55 },
  { name: 'SOFA, 3 SEAT/BED', volume: 60 },
  { name: 'SOFA, SECTIONAL-2 PIECE', volume: 90 },
  { name: 'SOFA, SECTIONAL-2 PIECE WITH RECLINER', volume: 100 },
  { name: 'SOFA, SECTIONAL-3 PIECE', volume: 105 },
  { name: 'SOFA, SECTIONAL-3 PIECE WITH RECLINER', volume: 115 },
  { name: 'SOFA, SECTIONAL-4 PIECE', volume: 120 },
  { name: 'SOFA, SECTIONAL-4 PIECE WITH RECLINER', volume: 130 },
  { name: 'SOFA, SECTIONAL-5 PIECE', volume: 150 },
  { name: 'SOFA, SECTIONAL-5 PIECE WITH RECLINER', volume: 160 },
  { name: 'SPEAKER, LG.', volume: 13 },
  { name: 'SPEAKER, REGULAR', volume: 8 },
  { name: 'STAND, MED.', volume: 8 },
  { name: 'STAND, SM.', volume: 5 },
  { name: 'STATUE, MEDIUM', volume: 15 },
  { name: 'STATUE, SMALL (PBO)', volume: 10 },
  { name: 'STEREO CABINET', volume: 18 },
  { name: 'STEREO SYSTEM (PBO)', volume: 14 },
  { name: 'STOOL BAR', volume: 3 },
  { name: 'STOOL, SM.', volume: 5 },
  { name: 'STOVE', volume: 35 },
  { name: 'STROLLER', volume: 17 },
  { name: 'STROLLER DOUBLE', volume: 22 },
  { name: 'STROLLER TRIPPLE', volume: 30 },
  { name: 'SUITCASE SM.', volume: 7 },
  { name: 'SUITCASE, LG.', volume: 9 },
  { name: 'SUITCASE, MED.', volume: 8 },
  { name: 'SURF BOARD', volume: 8 },
  { name: 'T.V. STAND (LARGE)', volume: 24 },
  { name: 'T.V. STAND (MEDIUM)', volume: 16 },
  { name: 'T.V. STAND (SMALL)', volume: 8 },
  { name: 'T.V. 20 (OR SMALLER)', volume: 7 },
  { name: 'T.V. BIG SCREEN', volume: 58 },
  { name: 'T.V. FLAT SCREEN 60+', volume: 22 },
  { name: 'T.V. FLAT SCREEN- 15-32', volume: 12 },
  { name: 'T.V. FLAT SCREEN- 33-60', volume: 17 },
  { name: 'T.V. FLAT SCREEN- 60-95', volume: 22 },
  { name: 'T.V. OVER 21 TO 39', volume: 13 },
  { name: 'T.V. STAND (LOW PROFILE)', volume: 16 },
  { name: 'TABLE LAMP, LARGE', volume: 16 },
  { name: 'TABLE, ACCENT', volume: 4 },
  { name: 'TABLE, CHANGING', volume: 20 },
  { name: 'TABLE, COFFEE', volume: 15 },
  { name: 'TABLE, CONFERENCE', volume: 75 },
  { name: 'TABLE, DINING', volume: 35 },
  { name: 'TABLE, DROP LEAF', volume: 18 },
  { name: 'TABLE, END', volume: 7 },
  { name: 'TABLE, ENTRANCE', volume: 20 },
  { name: 'TABLE, FOLDING', volume: 7 },
  { name: 'TABLE, GLASS TOP', volume: 8 },
  { name: 'TABLE, KITCHEN', volume: 25 },
  { name: 'TABLE, KITCHEN (SM.)', volume: 12 },
  { name: 'TABLE, SIDE', volume: 16 },
  { name: 'TABLE, SOFA', volume: 15 },
  { name: 'TABLE, TELEPHONE', volume: 5 },
  { name: 'TABLE, VANITY', volume: 16 },
  { name: 'TEA CART', volume: 10 },
  { name: 'TENT EX LARGE', volume: 40 },
  { name: 'TENT LARGE', volume: 30 },
  { name: 'TENT MEDIUM', volume: 20 },
  { name: 'TENT SMALL', volume: 10 },
  { name: 'TIRE (FOR CAR)', volume: 7 },
  { name: 'TOASTER OVEN (PBO)', volume: 2 },
  { name: 'TODDLER BED', volume: 23 },
  { name: 'TOOL BOX, LG. (OVER TO 300 LBS)', volume: 50 },
  { name: 'TOOL BOX, LG. (UP TO 300 LBS)', volume: 25 },
  { name: 'TOOL BOX, SM.', volume: 8 },
  { name: 'TOOL GANG BOX', volume: 55 },
  { name: 'TOOLS GARDEN', volume: 8 },
  { name: 'TOY CAR (FOR KIDS)', volume: 65 },
  { name: 'TRAMPOLINE, SMALL', volume: 28 },
  { name: 'TREADMILL', volume: 30 },
  { name: 'TRUNK, LARGE', volume: 12 },
  { name: 'TRUNK, SMALL', volume: 8 },
  { name: 'TWIN MATTRESS ONLY', volume: 18 },
  { name: 'TYPEWRITER (PBO)', volume: 3 },
  { name: 'VACUUM CLEANER', volume: 5 },
  { name: 'VANITY, BENCH', volume: 3 },
  { name: 'VANITY, DRESSER', volume: 20 },
  { name: 'WALL SHELVES', volume: 13 },
  { name: 'WALL UNIT 1 PIECE', volume: 30 },
  { name: 'WALL UNIT 2 PIECE', volume: 60 },
  { name: 'WALL UNIT 3 PIECE', volume: 120 },
  { name: 'WALL UNIT 4 PIECE', volume: 180 },
  { name: 'WARDROBE CLOSET', volume: 25 },
  { name: 'WASHER/DRYER COMBO', volume: 70 },
  { name: 'WASHING MACHINE', volume: 35 },
  { name: 'WATER COOLER', volume: 7 },
  { name: 'WEIGHT BENCH', volume: 16 },
  { name: 'WHEELBARROW', volume: 11 },
  { name: 'WICKER CHAIR', volume: 10 },
  { name: 'WICKER TABLE', volume: 15 },
  { name: 'WINE RACK, SMALL', volume: 7 },
  { name: 'WORK BENCH, REG.', volume: 35 },
  { name: 'WORK BENCH, SM.', volume: 18 },
];
